
from pathlib import Path
import torch

BASE_DIR    = Path(__file__).resolve().parent
PROJECT_DIR = BASE_DIR.parent

PHASE7_RESULTS_DIR = PROJECT_DIR / "results" / "phase_7"
PHASE7_SIGNALS     = PHASE7_RESULTS_DIR / "daily_signals_all.csv"
PHASE7_TRADES      = PHASE7_RESULTS_DIR / "trade_log.csv"
PHASE7_PORTFOLIO   = PHASE7_RESULTS_DIR / "portfolio_timeseries.csv"

PHASE1_LABEL_DIR = PROJECT_DIR / "results" / "phase_1" / "data" / "labelled"

RESULTS_DIR = PROJECT_DIR / "results" / "phase_8"
PLOTS_DIR   = RESULTS_DIR / "plots"
LOG_DIR     = RESULTS_DIR / "logs"

for d in [RESULTS_DIR, PLOTS_DIR, LOG_DIR]:
    d.mkdir(parents=True, exist_ok=True)

NIFTY_50_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "BAJFINANCE.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "HCLTECH.NS",
    "SUNPHARMA.NS", "TITAN.NS", "WIPRO.NS", "ULTRACEMCO.NS", "NESTLEIND.NS",
    "BAJAJFINSV.NS", "NTPC.NS", "POWERGRID.NS", "TECHM.NS", "ONGC.NS",
    "TATAMOTORS.NS", "TATASTEEL.NS", "JSWSTEEL.NS", "M&M.NS", "HINDALCO.NS",
    "COALINDIA.NS", "DRREDDY.NS", "DIVISLAB.NS", "CIPLA.NS", "APOLLOHOSP.NS",
    "ADANIPORTS.NS", "ADANIENT.NS", "GRASIM.NS", "HDFCLIFE.NS", "SBILIFE.NS",
    "SHRIRAMFIN.NS", "BPCL.NS", "EICHERMOT.NS", "HEROMOTOCO.NS", "INDUSINDBK.NS",
    "BRITANNIA.NS", "ITC.NS", "BAJAJ-AUTO.NS", "BEL.NS", "TRENT.NS",
]

ZERODHA_BROKERAGE_PCT     = 0.0
ZERODHA_STT_PCT           = 0.001
ZERODHA_EXCHANGE_TXN_PCT  = 0.0000345
ZERODHA_GST_PCT           = 0.18
ZERODHA_SEBI_PCT          = 0.000001
ZERODHA_STAMP_DUTY_PCT    = 0.00015
SLIPPAGE_PCT              = 0.0005

INITIAL_CAPITAL = 10_00_000
EVAL_START      = "2024-01-01"
EVAL_END        = "2024-12-31"
RISK_FREE_RATE  = 0.07
TRADING_DAYS_PER_YEAR = 252

EQUAL_WEIGHT = True
MAX_POSITIONS = 15
STOP_LOSS_PCT = 0.05
MIN_HOLDING_DAYS = 3

KITE_API_KEY    = ""
KITE_API_SECRET = ""
PAPER_TRADE_MODE = True

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

